export const homeData = [
  {
    id: 1,
    name: "Vingadores: Guerra...",
    rating: 4.7,
    time: "2h36m",
    desc: "Em Vingadores: Guerra Infinita, Thanos (Josh Brolin) enfim chega à Terra, disposto a reunir as Joias do Infinito. Para enfrentá-lo, os Vingadores precisam unir forças com os Guardiões da Galáxia, ao mesmo tempo em que lidam com desavenças entre alguns de seus integrantes.",
    director: "Joe Russo, Anthony Russo",
    country: "Estados Unidos",
    genres: "Aventura, Ação, Fantasia",
    releaseYear: 2019,
    cover: "../images/home1.jpg",
    video: "https://www.youtube.com/watch?v=t_ULBP6V9bg",
  },
  {
    id: 2,
    name: "Tudo Bem no Natal...",
    rating: 4.1,
    time: "1h40m",
    desc: "Em Tudo Bem no Natal que Vem, Jorge (Leandro Hassum) é um homem rabugento que sempre odiou o Natal e costuma fazer de tudo para evitar as comemorações dessa data. Na véspera do feriado, ele cai do telhado e bate a cabeça.",
    director: "Roberto Santucci",
    country: "Brasil",
    genres: "Drama, Comédia",
    releaseYear: 2020,
    cover: "../images/home2.webp",
    video: "https://www.youtube.com/watch?v=W6nIRxz6RVE",
  },
  {
    id: 3,
    name: "A Cinco Passos de Você",
    rating: 4.2,
    time: "1h57m",
    desc: "No enredo de A Cinco Passos de Você, Stella Grant (Haley Lu Richardson), aos dezesseis anos de idade, é diferente da maior parte dos adolescentes: devido a uma fibrose cística, ela passa muito tempo no hospital, entre tratamentos e acompanhamento médico. Um dia, conhece Will Newman (Cole Sprouse), garoto que sofre da mesma doença que ela.",
    director: "Justin Baldoni",
    country: "Estados Unidos",
    genres: "Drama, Romance",
    releaseYear: 2019,
    cover: "../images/home3.jpg",
    video: "https://www.youtube.com/watch?v=EbzvDk-bQM4",
  },
  {
    id: 4,
    name: "O Poço",
    rating: 3.8,
    time: "1h34m",
    desc: "Exibido pela Netflix, O Poço conta a história de um lugar misterioso, uma prisão indescritível, um buraco profundo. Dois reclusos que vivem em cada nível. Um número desconhecido de níveis. Uma plataforma descendente contendo comida para todos eles.",
    director: "Galder Gaztelu-Urrutia",
    country: "Espanha",
    genres: "Terror",
    releaseYear: 2022,
    cover: "../images/home5.jpg",
    video: "https://www.youtube.com/watch?v=LBmoEwPXQw0",
  },
  {
    id: 5,
    name: "O Quarto de Jack",
    rating: 4.6,
    time: "1h58m",
    desc: "Em O Quarto de Jack, Joy (Brie Larson) e seu filho Jack (Jacob Tremblay) vivem isolados em um quarto. O único contato que ambos têm com o mundo exterior é a visita periódica do Velho Nick (Sean Bridgers), que os mantém em cativeiro.",
    director: "Lenny Abrahamson",
    country: "Estados Unidos",
    genres: "Drama",
    releaseYear: 2016,
    cover: "../images/home4.jpg",
    video: "https://www.youtube.com/watch?v=Ri_eUI7UI8I",
  },
  {
    id: 6,
    name: "Animais Fantásticos",
    rating: 4.4,
    time: "2h13m",
    desc: "O excêntrico magizoologista Newt Scamander (Eddie Redmayne) chega à cidade de Nova York levando com muito zelo sua preciosa maleta, um objeto mágico onde ele carrega fantásticos animais do mundo da magia que coletou durante as suas viagens.",
    director: "David Yates",
    country: "Inglaterra",
    genres: "Fantasia/Aventura",
    releaseYear: 2016,
    cover: "../images/home6.jpg",
    video: "https://www.youtube.com/watch?v=HRdIQ5oLHG4",
  },
  {
    id: 7,
    name: "A Origem",
    rating: 4.6,
    time: "2h28m",
    desc: "Em um mundo onde é possível entrar na mente humana, Cobb (Leonardo DiCaprio) está entre os melhores na arte de roubar segredos valiosos do inconsciente, durante o estado de sono.",
    director: "Christopher Nolan",
    country: "Estados Unidos",
    genres: "Ficção Científica, Suspense",
    releaseYear: 2010,
    cover: "../images/home7.jpg",
    video: "https://www.youtube.com/watch?v=HiixbtN-O24",
  },
  {
    id: 8,
    name: "Up - Altas Aventuras",
    rating: 4.6,
    time: "1h35m",
    desc: "Carl Fredricksen (Edward Asner) é um vendedor de balões que, aos 78 anos, está prestes a perder a casa em que sempre viveu com sua esposa, a falecida Ellie. O terreno onde a casa fica localizada interessa a um empresário, que deseja construir no local um edifício.",
    director: "Pete Docter, Bob Peterson",
    country: "Estados Unidos",
    genres: "Animação, Família, Fantasia",
    releaseYear: 2009,
    cover: "../images/home8.jpg",
    video: "https://www.youtube.com/watch?v=j8etbVnzhtU",
  },
  {
    id: 9,
    name: "Titanic",
    rating: 4.6,
    time: "3h14m",
    desc: "Jack Dawson (Leonardo DiCaprio) é um jovem aventureiro que, na mesa de jogo, ganha uma passagem para a primeira viagem do transatlântico Titanic. Trata-se de um luxuoso e imponente navio, anunciado na época como inafundável, que parte para os Estados Unidos.",
    director: "James Cameron",
    country: "Inglaterra",
    genres: "Drama/Romance",
    releaseYear: 1998,
    cover: "../images/home9.jpg",
    video: "https://www.youtube.com/watch?v=0uWkF-gz7jI",
  },
  {
    id: 10,
    name: "Em Ritmo de Fuga",
    rating: 4.3,
    time: "1h53m",
    desc: "Em Ritmo de Fuga, o jovem Baby (Ansel Elgort) tem uma mania curiosa: precisa ouvir músicas o tempo todo para silenciar o zumbido que perturba seus ouvidos desde um acidente na infância.",
    director: "Edgar Wright",
    country: "Estados Unidos / Inglaterra",
    genres: "Drama/Romance",
    releaseYear: 2017,
    cover: "../images/home10.webp",
    video: "https://www.youtube.com/watch?v=TJrKYWPBTrc",
  },
  {
    id: 11,
    name: "Kingsman: O Círculo...",
    rating: 4.1,
    time: "2h21m",
    desc: "Um súbito e grandioso ataque de mísseis praticamente elimina o Kingsman, que conta apenas com Eggsy (Taron Egerton) e Merlin (Mark Strong) como remanescentes. Em busca de ajuda, eles partem para os Estados Unidos à procura da Statesman, uma organização secreta de espionagem...",
    director: "Matthew Vaughn",
    country: "Reino Unido / Estados Unidos",
    genres: "Ação, Espionagem, Comédia",
    releaseYear: 2017,
    cover: "../images/home11.jpg",
    video: "https://www.youtube.com/watch?v=LqehHzvyaKw",
  },
  {
    id: 12,
    name: "Milagre na Cela 7",
    rating: 4.5,
    time: "2h12m",
    desc: "Separado de sua filha por ser acusado de um crime que não cometeu, um homem com deficiência intelectual precisa provar sua inocência ao ser preso pela morte da filha de um comandante. Ele passa a contar com a ajuda de seus companheiros de cela e de quem também está do outro lado das grades.",
    director: "Mehmet Ada Öztekin",
    country: "Turquia",
    genres: "Drama",
    releaseYear: 2019,
    cover: "../images/home12.jpg",
    video: "https://www.youtube.com/watch?v=Go3OQn1YomI",
  }
]