export const homeData = [
  {
    id: 1,
    name: "Animais Fantásticos",
    rating: 4.4,
    time: "2h13m",
    desc: "O excêntrico magizoologista Newt Scamander (Eddie Redmayne) chega à cidade de Nova York levando com muito zelo sua preciosa maleta, um objeto mágico onde ele carrega fantásticos animais do mundo da magia que coletou durante as suas viagens.",
    director: "David Yates",
    country: "Inglaterra",
    genres: "Fantasia/Aventura",
    releaseYear: 2016,
    cover: "../images/home1.jpg",
    video: "https://www.youtube.com/watch?v=HRdIQ5oLHG4",
  },
  {
    id: 2,
    name: "Tudo Bem no Natal...",
    rating: 4.1,
    time: "1h40m",
    desc: "Em Tudo Bem no Natal que Vem, Jorge (Leandro Hassum) é um homem rabugento que sempre odiou o Natal e costuma fazer de tudo para evitar as comemorações dessa data. Na véspera do feriado, ele cai do telhado e bate a cabeça.",
    director: "Roberto Santucci",
    country: "Brasil",
    genres: "Drama, Comédia",
    releaseYear: 2020,
    cover: "../images/home2.webp",
    video: "https://www.youtube.com/watch?v=W6nIRxz6RVE",
  },
  {
    id: 3,
    name: "A Cinco Passos de Você",
    rating: 4.2,
    time: "1h57m",
    desc: "No enredo de A Cinco Passos de Você, Stella Grant (Haley Lu Richardson), aos dezesseis anos de idade, é diferente da maior parte dos adolescentes: devido a uma fibrose cística, ela passa muito tempo no hospital, entre tratamentos e acompanhamento médico. Um dia, conhece Will Newman (Cole Sprouse), garoto que sofre da mesma doença que ela.",
    director: "Justin Baldoni",
    country: "Estados Unidos",
    genres: "Drama, Romance",
    releaseYear: 2019,
    cover: "../images/home3.jpg",
    video: "https://www.youtube.com/watch?v=EbzvDk-bQM4",
  },
  {
    id: 4,
    name: "O Poço",
    rating: 3.8,
    time: "1h34m",
    desc: "Exibido pela Netflix, O Poço conta a história de um lugar misterioso, uma prisão indescritível, um buraco profundo. Dois reclusos que vivem em cada nível. Um número desconhecido de níveis. Uma plataforma descendente contendo comida para todos eles.",
    director: "Galder Gaztelu-Urrutia",
    country: "Espanha",
    genres: "Terror",
    releaseYear: 2022,
    cover: "../images/home5.jpg",
    video: "https://www.youtube.com/watch?v=LBmoEwPXQw0",
  },
  {
    id: 5,
    name: "O Quarto de Jack",
    rating: 4.6,
    time: "1h58m",
    desc: "Em O Quarto de Jack, Joy (Brie Larson) e seu filho Jack (Jacob Tremblay) vivem isolados em um quarto. O único contato que ambos têm com o mundo exterior é a visita periódica do Velho Nick (Sean Bridgers), que os mantém em cativeiro. Joy faz o possível para tornar suportável a vida no local, mas não vê a hora de deixá-lo.",
    director: "Lenny Abrahamson",
    country: "Estados Unidos",
    genres: "Drama",
    releaseYear: 2016,
    cover: "../images/home4.jpg",
    video: "https://www.youtube.com/watch?v=Ri_eUI7UI8I",
  },
]